module.exports.geography = `
Geography (from Greek: γεωγραφία, geographia, literally "earth description")[1] is a field of science devoted to the study of the lands, features, inhabitants, and phenomena of the Earth and planets.[2] The first person to use the word γεωγραφία was Eratosthenes (276–194 BC).[3] Geography is an all-encompassing discipline that seeks an understanding of Earth and its human and natural complexities—not merely where objects are, but also how they have changed and come to be.

Geography is often defined in terms of two branches: human geography and physical geography.[4][5] Human geography deals with the study of people and their communities, cultures, economies, and interactions with the environment by studying their relations with and across space and place.[6] Physical geography deals with the study of processes and patterns in the natural environment like the atmosphere, hydrosphere, biosphere, and geosphere.

The four historical traditions in geographical research are: spatial analyses of natural and the human phenomena, area studies of places and regions, studies of human-land relationships, and the Earth sciences.[7] Geography has been called "the world discipline"[8] and "the bridge between the human and the physical sciences".[9]

Geography is a systematic study of the Universe and its features. Traditionally, geography has been associated with cartography and place names. Although many geographers are trained in toponymy and cartology, this is not their main preoccupation. Geographers study the space and the temporal database distribution of phenomena, processes, and features as well as the interaction of humans and their environment.[10] Because space and place affect a variety of topics, such as economics, health, climate, plants and animals, geography is highly interdisciplinary. The interdisciplinary nature of the geographical approach depends on an attentiveness to the relationship between physical and human phenomena and its spatial patterns.[11]

Names of places...are not geography...know by heart a whole gazetteer full of them would not, in itself, constitute anyone a geographer. Geography has higher aims than this: it seeks to classify phenomena (alike of the natural and of the political world, in so far as it treats of the latter), to compare, to generalize, to ascend from effects to causes, and, in doing so, to trace out the laws of nature and to mark their influences upon man. This is 'a description of the world'—that is Geography. In a word Geography is a Science—a thing not of mere names but of argument and reason, of cause and effect.[12]

— William Hughes, 1863
Just as all phenomena exist in time and thus have a history, they also exist in space and have a geography.[13]

— United States National Research Council, 1997
Geography as a discipline can be split broadly into two main subsidiary fields: human geography and physical geography. The former largely focuses on the built environment and how humans create, view, manage, and influence space. The latter examines the natural environment, and how organisms, climate, soil, water, and landforms produce and interact.[14] The difference between these approaches led to a third field, environmental geography, which combines physical and human geography and concerns the interactions between the environment and humans.[10]
`;

module.exports.animals = `
Animals are multicellular eukaryotic organisms that form the biological kingdom Animalia. With few exceptions, animals consume organic material, breathe oxygen, are able to move, can reproduce sexually, and grow from a hollow sphere of cells, the blastula, during embryonic development. Over 1.5 million living animal species have been described—of which around 1 million are insects—but it has been estimated there are over 7 million animal species in total. Animals range in length from 8.5 millionths of a metre to 33.6 metres (110 ft) and have complex interactions with each other and their environments, forming intricate food webs. The category includes humans, but in colloquial use the term animal often refers only to non-human animals. The study of non-human animals is known as zoology.

Most living animal species are in the Bilateria, a clade whose members have a bilaterally symmetric body plan. The Bilateria include the protostomes—in which many groups of invertebrates are found, such as nematodes, arthropods, and molluscs—and the deuterostomes, containing the echinoderms and chordates (including the vertebrates). Life forms interpreted as early animals were present in the Ediacaran biota of the late Precambrian. Many modern animal phyla became clearly established in the fossil record as marine species during the Cambrian explosion which began around 542 million years ago. 6,331 groups of genes common to all living animals have been identified; these may have arisen from a single common ancestor that lived 650 million years ago.

Aristotle divided animals into those with blood and those without. Carl Linnaeus created the first hierarchical biological classification for animals in 1758 with his Systema Naturae, which Jean-Baptiste Lamarck expanded into 14 phyla by 1809. In 1874, Ernst Haeckel divided the animal kingdom into the multicellular Metazoa (now synonymous with Animalia) and the Protozoa, single-celled organisms no longer considered animals. In modern times, the biological classification of animals relies on advanced techniques, such as molecular phylogenetics, which are effective at demonstrating the evolutionary relationships between animal taxa.

Humans make use of many other animal species for food, including meat, milk, and eggs; for materials, such as leather and wool; as pets; and as working animals for power and transport. Dogs have been used in hunting, while many terrestrial and aquatic animals are hunted for sport. Non-human animals have appeared in art from the earliest times and are featured in mythology and religion.

Animals have several characteristics that set them apart from other living things. Animals are eukaryotic and multicellular,[7][8] unlike bacteria, which are prokaryotic, and unlike protists, which are eukaryotic but unicellular. Unlike plants and algae, which produce their own nutrients[9] animals are heterotrophic,[8][10] feeding on organic material and digesting it internally.[11] With very few exceptions, animals breathe oxygen and respire aerobically.[12] All animals are motile[13] (able to spontaneously move their bodies) during at least part of their life cycle, but some animals, such as sponges, corals, mussels, and barnacles, later become sessile. The blastula is a stage in embryonic development that is unique to most animals,[14] allowing cells to be differentiated into specialised tissues and organs.

Structure
All animals are composed of cells, surrounded by a characteristic extracellular matrix composed of collagen and elastic glycoproteins.[15] During development, the animal extracellular matrix forms a relatively flexible framework upon which cells can move about and be reorganised, making the formation of complex structures possible. This may be calcified, forming structures such as shells, bones, and spicules.[16] In contrast, the cells of other multicellular organisms (primarily algae, plants, and fungi) are held in place by cell walls, and so develop by progressive growth.[17] Animal cells uniquely possess the cell junctions called tight junctions, gap junctions, and desmosomes.[18]

With few exceptions—in particular, the sponges and placozoans—animal bodies are differentiated into tissues.[19] These include muscles, which enable locomotion, and nerve tissues, which transmit signals and coordinate the body. Typically, there is also an internal digestive chamber with either one opening (as in flatworms) or two openings (as in deuterostomes).[20]
Nearly all animals make use of some form of sexual reproduction.[21] They produce haploid gametes by meiosis; the smaller, motile gametes are spermatozoa and the larger, non-motile gametes are ova.[22] These fuse to form zygotes,[23] which develop via mitosis into a hollow sphere, called a blastula. In sponges, blastula larvae swim to a new location, attach to the seabed, and develop into a new sponge.[24] In most other groups, the blastula undergoes more complicated rearrangement.[25] It first invaginates to form a gastrula with a digestive chamber and two separate germ layers, an external ectoderm and an internal endoderm.[26] In most cases, a third germ layer, the mesoderm, also develops between them.[27] These germ layers then differentiate to form tissues and organs.[28]

Repeated instances of mating with a close relative during sexual reproduction generally leads to inbreeding depression within a population due to the increased prevalence of harmful recessive traits.[29][30] Animals have evolved numerous mechanisms for avoiding close inbreeding.[31] In some species, such as the splendid fairywren (Malurus splendens), females benefit by mating with multiple males, thus producing more offspring of higher genetic quality.[32]

Some animals are capable of asexual reproduction, which often results in a genetic clone of the parent. This may take place through fragmentation; budding, such as in Hydra and other cnidarians; or parthenogenesis, where fertile eggs are produced without mating, such as in aphids.[33][34]

Animals are categorised into ecological groups depending on how they obtain or consume organic material, including carnivores, herbivores, omnivores, detritivores,[35] and parasites.[36] Interactions between animals form complex food webs. In carnivorous or omnivorous species, predation is a consumer-resource interaction where a predator feeds on another organism (called its prey).[37] Selective pressures imposed on one another lead to an evolutionary arms race between predator and prey, resulting in various anti-predator adaptations.[38][39] Almost all multicellular predators are animals.[40] Some consumers use multiple methods; for example, in parasitoid wasps, the larvae feed on the hosts' living tissues, killing them in the process,[41] but the adults primarily consume nectar from flowers.[42] Other animals may have very specific feeding behaviours, such as hawksbill sea turtles that primarily eat sponges.[43]


Hydrothermal vent mussels and shrimps
Most animals rely on the energy produced by plants through photosynthesis. Herbivores eat plant material directly, while carnivores, and other animals on higher trophic levels, typically acquire energy (in the form of reduced carbon) by eating other animals. The carbohydrates, lipids, proteins, and other biomolecules are broken down to allow the animal to grow and to sustain biological processes such as locomotion.[44][45][46] Animals living close to hydrothermal vents and cold seeps on the dark sea floor do not depend on the energy of sunlight.[47] Rather, archaea and bacteria in these locations produce organic matter through chemosynthesis (by oxidizing inorganic compounds, such as methane) and form the base of the local food web.[48]

`;

